export enum RequirementTypeEnum {
  MAJOR_REQUIRED = 'MAJOR_REQUIRED',
  MAJOR_ELECTIVE = 'MAJOR_ELECTIVE',
  MAJOR_BASIC = 'MAJOR_BASIC',
  GENERAL_REQUIRED = 'GENERAL_REQUIRED',
  REQUIRED_GENERAL_ELECTIVE = 'REQUIRED_GENERAL_ELECTIVE',
  GENERAL_ELECTIVE = 'GENERAL_ELECTIVE',
  FREE_ELECTIVE = 'FREE_ELECTIVE',
  MD_MAJOR_ELECTIVE = 'MD_MAJOR_ELECTIVE',
}
