# 1. Node.js 21 공식 이미지
FROM node:21-alpine

# 2. 작업 디렉토리
WORKDIR /usr/src/app

# 3. package.json만 먼저 복사 (캐시 활용)
COPY package*.json ./

# 4. 의존성 설치
RUN npm install

# 5. 나머지 앱 코드 복사
COPY . .

# 6. 빌드
RUN npm run build

# 7. 포트 개방
EXPOSE 5000

# 8. 앱 실행
CMD ["npm", "run", "start:prod"]

# docker build -t hsu-auto-scheduler-be-docker-image .
# docker run -d --name hsu-auto-scheduler-be-docker-container -p 80:5000 --env-file .env hsu-auto-scheduler-be-docker-image